import type { Category, Product } from './types';
import { storage } from './storage';

export function initializeData(): void {
  const existingProducts = storage.getProducts();
  if (existingProducts.length > 0) {
    return;
  }

  const categories: Category[] = [
    { id: 'cat-1', nameEn: 'Electronics', nameSo: 'Elektarooniga', displayOrder: 1 },
    { id: 'cat-2', nameEn: 'Food & Beverages', nameSo: 'Cunto iyo Cabitaan', displayOrder: 2 },
    { id: 'cat-3', nameEn: 'Clothing', nameSo: 'Dharka', displayOrder: 3 },
    { id: 'cat-4', nameEn: 'Household', nameSo: 'Guriga', displayOrder: 4 },
    { id: 'cat-5', nameEn: 'Personal Care', nameSo: 'Daryeelka Shaqsiga', displayOrder: 5 },
    { id: 'cat-6', nameEn: 'Other', nameSo: 'Kale', displayOrder: 6 },
  ];

  const products: Product[] = [
    {
      id: 'prod-1',
      nameEn: 'Samsung Galaxy A54',
      nameSo: 'Samsung Galaxy A54',
      barcode: '8806094935554',
      priceUsd: 350,
      categoryId: 'cat-1',
      stockQuantity: 15,
      restockThreshold: 5,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-2',
      nameEn: 'USB-C Cable',
      nameSo: 'Fiilo USB-C',
      barcode: '1234567890123',
      priceUsd: 5,
      categoryId: 'cat-1',
      stockQuantity: 50,
      restockThreshold: 10,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-3',
      nameEn: 'Rice 5kg',
      nameSo: 'Bariis 5kg',
      barcode: '2234567890123',
      priceUsd: 12,
      categoryId: 'cat-2',
      stockQuantity: 100,
      restockThreshold: 20,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-4',
      nameEn: 'Cooking Oil 1L',
      nameSo: 'Saliid 1L',
      barcode: '3234567890123',
      priceUsd: 3.5,
      categoryId: 'cat-2',
      stockQuantity: 80,
      restockThreshold: 15,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-5',
      nameEn: 'Tea 500g',
      nameSo: 'Shaah 500g',
      barcode: '4234567890123',
      priceUsd: 8,
      categoryId: 'cat-2',
      stockQuantity: 60,
      restockThreshold: 10,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-6',
      nameEn: 'Men\'s T-Shirt',
      nameSo: 'Shaati Ragga',
      barcode: '5234567890123',
      priceUsd: 15,
      categoryId: 'cat-3',
      stockQuantity: 40,
      restockThreshold: 8,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-7',
      nameEn: 'Women\'s Scarf',
      nameSo: 'Garbasaar Haweenka',
      barcode: '6234567890123',
      priceUsd: 10,
      categoryId: 'cat-3',
      stockQuantity: 3,
      restockThreshold: 5,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-8',
      nameEn: 'Dish Soap',
      nameSo: 'Saabuun Saxan',
      barcode: '7234567890123',
      priceUsd: 2.5,
      categoryId: 'cat-4',
      stockQuantity: 70,
      restockThreshold: 15,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-9',
      nameEn: 'Laundry Detergent 2kg',
      nameSo: 'Saabuun Dharka 2kg',
      barcode: '8234567890123',
      priceUsd: 7,
      categoryId: 'cat-4',
      stockQuantity: 45,
      restockThreshold: 10,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-10',
      nameEn: 'Body Lotion',
      nameSo: 'Lotion Jirka',
      barcode: '9234567890123',
      priceUsd: 6,
      categoryId: 'cat-5',
      stockQuantity: 35,
      restockThreshold: 8,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-11',
      nameEn: 'Toothpaste',
      nameSo: 'Cajiinta Ilkaha',
      barcode: '1034567890123',
      priceUsd: 3,
      categoryId: 'cat-5',
      stockQuantity: 90,
      restockThreshold: 20,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
    {
      id: 'prod-12',
      nameEn: 'Notebook A4',
      nameSo: 'Buug A4',
      barcode: '1134567890123',
      priceUsd: 2,
      categoryId: 'cat-6',
      stockQuantity: 120,
      restockThreshold: 25,
      isActive: true,
      createdAt: new Date().toISOString(),
      updatedAt: new Date().toISOString(),
    },
  ];

  storage.setCategories(categories);
  storage.setProducts(products);
}
